INSERT INTO user(email, nick_name, password_hash, role) VALUES ('test@test.com', 'test', '$2a$10$dA6bymqtv0PREkhniUdIz.xJMEAZcYveB.zNbqXlXtQKoWBH7dzyK', 'USER');
INSERT INTO user(email, nick_name, password_hash, role) VALUES ('hope@test.com', 'hope', '$2a$10$dA6bymqtv0PREkhniUdIz.xJMEAZcYveB.zNbqXlXtQKoWBH7dzyK', 'USER');
INSERT INTO user(email, nick_name, password_hash, role) VALUES ('ios@test.com', 'iOS', '$22a$10$dA6bymqtv0PREkhniUdIz.xJMEAZcYveB.zNbqXlXtQKoWBH7dzyK', 'USER');
INSERT INTO user(email, nick_name, password_hash, role) VALUES ('android@test.com', 'android', '$2a$10$XWAdSxEOFTkUFvNV-NhNHOSY.CkEOJQJsnjffCazNHdMZM1ZZG.8a', 'USER');
INSERT INTO user(email, nick_name, password_hash, role) VALUES ('windows@test.com', 'windows', '$2a$10$XWAdSxEOFTkUFvNV-NhNHOSY.CkEOJQJsnjffCazNHdMZM1ZZG.8a', 'USER');

INSERT INTO course_info(goals, textbook, description, criteria, notice, disabilities) VALUES ('This course provides students with an understanding of how animals adapt physiologically to environmental challenge and addressed the basic physical and chemical principles that underlie physiological processes. Several biological systems are considered including transport through plasma membrane, signal transduction, nervous, endocrine, and muscle.', 'Essentials of Physiology, Korean Language Edition, Shin-Sung Kang et al., 2013, 4h Edition, Science plus (Cengage Learning, ISBN-13: 92017-08-14 13:00:003-63-8)', 'Introduction to the physical and chemical principles governing the lives of animals.\nMethods : Oral presentation', 'The two exams, mid-term and final, will cover lectures given in class and pertinent information from the textbook.', 'There is no policy of required attendance. However, it is unlikely that you will earn an acceptable grade if you do not attend class regularly. Reading the material in the textbook beforehand will help you better understand the lecture. Shortly after each lecture you should read the material in the textbook to make sure that you fully understand the material that was covered.', 'A. Hearing Impaired : first row priority seating, Class transcripts may also be provided. \nB. Develpmenatlly Challenged : Extended Test Period \nC. Brain lesions : Extended Test Period, Class transcripts may also be provided \nD. Visually Impaired : Larger Font test will be provided \nOther : Aid offered dependant on specific disabilities \n\n\n\n\n\nC. Brain lesions : Extended Test Period, Class transcripts may also be provided\n\n\nD. Visually Impaired : Larger Font test will be provided\n\n\nOther : Aid offered dependant on specific disabilities');
INSERT INTO course_info(goals, textbook, description, criteria, notice, disabilities) VALUES ('이 수업은 고고학의 기본자료로서 토기, 석기, 금속기 유물의 질적, 그리고 형태적 속성을 파악하고 분석하여 인간행위와 연결시켜 이해 할 수 있는 능력을 가질 수 있도록 훈련시키기 위해 이 수업이 마련되었다. 이 수업을 통해 학생들은 첫째, 유물의 질적 형태적 특성들을 관찰하고 분석하여 파악된 특성을 도면으로 제시하고 인간행위의 차원에서 서술하여 유물을 제시 보고할 수 있도록 한다. 둘째, 유물의 속성을 파악하고 분석, 평가, 선택하여 형식을 정의하거나 배열함으로써 고고학 자료의 체계를 정의하고 제수할 수 있도록 한다.', 'Handbook of Archaeological Methods Vol. 2 [Maschner and Chippindale(eds) 2005, Altamira Press)\nThe Archaeologist''s Laboratory(E. B. Banning, 2000, Springer)\nArchaeology in Practice(J. Balme and A. Paterson, 2014, Wiley and Blackwell)\nArchaeological Chemistry second edition(Z. Goffer, 2007, Wiley)\nPottery Tchnology(O. S. Rye, 1981, Taraxacum)\n토기연구법(칼라시노폴리 저, 이성주 역, 2005, 도서출판 고고)\nPottery Analysis(P. Rice, 1997, Chicago)\nLithics(William Anderfsky, 1998, Cambirdge mannuals in Archaeology, Cambridge)\nStone Tools in Human Evolution(J. J. Shea, 2017, Cambridge)\nUnderstanding Stone tools and Archaeological Sites(B. P. Kooyman, 2001, University of Calgary Press)', '1. 강의: 주요개념의 소개, 학습주제의 사전 및 사후 설명(40%)\n\n2. 발표토론: 교재를 읽고 프리젠테이션하고 토론함(40%)\n\n3. 토기 및 석기 실측 및 디스크립션(20%)', '* 과제\n\n실측도면과 유물 설명문 제출(가장 완벽한 것으로 토기 및 석기 5종)\n\n* 평가방법\n과제 30%\n중간 30%\n기말 30%\n출석및 기타 10%\n\n\n* 선수과목', '11월 중순부터 고고학 실습에 들어갈 예정이므로 이때부터 실습 및 과제 수행을 위해 여가시간을 활용할 수 있도록 해야 함', '장애의 정도에 따라 필요한 사안이 발생하면 최대한 편의 제공');
INSERT INTO course_info(goals, textbook, description, criteria, notice, disabilities) VALUES ('본 과목에서는 문화기술에 관한 주요 담론을 소개하고 필요한 개념적 정의들을 공유한다. 또한 문화콘텐츠 분야를 주 대상으로 하여 문화를 지원하는 기술들에 대한 제반 지식을 습득하고 프로세싱 언어를 통한 문화콘텐츠 저작 방안에 대해 습득한다.', '''문화기술개론'', 경북대학교출판부\n저자: 김상욱, 김항준, 임수연', '빔 프로젝트 활용한 PPT 강의', '중간 · 기말고사 (80%)\n출석 및 수업참여도 (20%)', '■ 출석이 80% 이상이며, 중간고사와 기말고사를 필하였을 경우에만 C 이상의 학점을 취득할 수 있다. \n■ 단 중간고사와 기말고사의 내용이 극히 부실할 경우에는 C 이하의 학점을 부과한다. \n■ 출석이 80% 이하의 경우에는 과제평가가 우수하더라도 감점할 수 있다. \n■ 중간평가 및 레포트 제출, 기말평가 등의 의무를 다하였다고 하더라도 출석이 현저하게 불량한 경우에는 최하의 성적을 부과하거나 낙제시킬 수 있다.', '가. 청각장애 학생 : 앞자리 지정석, 강의자료 File 제공(가능한 과목에 한함), 긴급 전달사항은 메모활용 등\n나. 지체장애 학생 : 시험시간연장 등\n다. 뇌병변장애 학생 : 시험시간연장, 강의자료 File 제공(가능한 과목에 한함) 등\n라. 시각장애 학생 : 시험지 확대복사제공 등\n마. 기타 장애정도에 따라 필요한 사안이 발생시 최대한 편의 제공함');
INSERT INTO course_info(goals, textbook, description, criteria, notice, disabilities) VALUES ('물리학을 바탕으로 전공 공부를 하는데 필요한 기초적인 물리적 사고를 익히고자 한다. 또한 물리의 기초 개념과 원리를 명확하고 논리적으로 이해하고 실제로 널리 알려진 응용을 통하여 개념과 이해를 강화하고자 한다.', '1. 교재: 대학 물리학 제8판(Physics for scientists and engineers with modern physics, 8th Edition) \nR.A.Serway-J.W.Jewett 저, 북스힐\n\n2. 참고문헌: 대학물리학(R.D.Knight원저, 2011, 북스힐), 대학물리학(Benson원저, 청문각)', '판서 및 PPT자료', '1. 과제; 연습문제 풀이\n2. 평가방법: 상대평가', '1. 출석미달자는 F학점 처리\n2. 중간(기말)고사 및 수시고사에 대한 공결 대상자(학칙에서 규정한 자)는 추가시험 실시', '1) 청각장애 학생: 앞자리 지정석, 강의자료 파일 제공, 메모 활용\n2) 지체장애 학생: 시험시간연장(추가 1시간이내)\n3) 뇌병변장애 학생: 시험시간연장(추가 1시간이내)\n4) 시각장애 학생: 시험지 확대복사 제공\n5) 기타 장애정도에 따라 필요한 사안이 발생시 최대한 편의 제공');
INSERT INTO course_info(goals, textbook, description, criteria, notice, disabilities) VALUES ('본 강좌는 화법의 원리와 방법론을 익히고, 다양한 언어 상황 속에서의 적용 과정을 실습함으로써 실용적이고도 수준 높은 화법 구사 능력을 체득하도록 함을 목적으로 한다. 이러한 목적을 통해 단순히 기술적 측면의 화술이 아니라 질적 수준을 갖는 화법 능력을 갖도록 한다. 이렇게 함으로써, 대학생으로서의 소양을 높이고 사회인으로서의 마음가짐을 갖도록 하는, 효용적 교양 강좌가 될 것이다. 우리는 누구나 말을 하고 들으면 살아간다. 여기에는 단순히 생활의 편이를 위한 수단으로서의 화법이 아닌 자신이 평가되는 기준으로서의 화법도 있다. 자신의 말하는 태도나 말솜씨를 통해 타인에게 자신이 평가되고, 토론회나 발표회를 통해서 자신의 사고 능력을 펼쳐 보이며, 취직을 위해서 구술면접이라는 중요한 절차를 통과해야만 한다. 이처럼 화법 능력의 배양은 대학생으로서 필히 준비하고 갖추어 두어야 할 중요한 소양이 된다. 이러한 소양의 향상을 위해, 본 강좌는 강의 방식을 통해서 ''화법의 개념'', ''화법의 구조와 특성'', ''화법의 기본 원리'', ''말하기와 듣기의 방법론'', ''언어 예절'', ''각종 화법모형''(면접, 토론, 프레젠테이션 등)에 대한 이론적 내용을 알게 하고, 나아가 실제적인 각종 실습을 통해서 화법의 실천적 측면을 익히도록 할 것이다.', '1. 교재-임지룡 외(2013), 삶을 위한 화법, 정림사.\n2. 참고문헌\n-구현정·전정미(2007), 화법의 이론과 실제, 박이정. \n-임칠성· 원진숙· 심영택· 이창덕(2004), 말꽝에서 말짱되기, 태학사.\n-이유빈(2005), 듣기형 인간, 비즈&북. \n-임규홍·나익주 옮김(2000), 당신도 말을 잘할 수 있다, 박이정.', '1. 이론 부분과 실제 부분이 병행되거나 실제 화법의 훈련을 위한 실습 시간을 갖는다. \n(1) 월요일 : 이론 수업 및 모의 활동\n(2) 금요일 : 소그룹 활동 및 5분 말하기\n\n2. 해당 주의 실습 과제는 필요에 따라 전시 수업 시간에 공지될 수 있다.', '1. 이론평가: 25% -지필평가(기말고사)\n\n2. 실습평가: 50% \n(1) 개인발표 30% - 5분말하기 \n(2) 조별발표 20% - 모의 프레젠테이션, 모의토론, 모의면접 등\n\n3. 보고서: 15%(과제 3개-각 5% 씩: 과제 결과의 완성도, 이해도, 작성의 성실도)\n\n4. 출석: 5%(1회 결석 시 총점 5점에서 1점 씩 감점-수업 시작 후 15분이 지나면 결석으로 간주)\n\n5. 수업참여도: 5%(소그룹 활동 참여도, 발표, 토론 준비도, 성실도)', '1. 화법 능력은 짧은 기간의 수련으로 신장될 성질이 아닙니다. 그러므로 이 강의에서는 화법의 개념과 원리에 대한 기본적인 이해를 바탕으로, 학교 생활 및 졸업 후 당면하게 될 중요한 언어 장면을 가정하여 말하기를 준비하고 실행하는 기회를 갖는 데 초점을 두고자 합니다. \n\n2. 이론 강의와 학생의 실습이 병행되므로, 실습 시 학생의 적극적인 수업 참여가 중요합니다. 강의 진행이나 수강 인원에 따라 실습 시간이나 기회가 조정될 수 있습니다.\n\n3. 최대한 교재와 실제 수업내용이 병행되도록 하겠지만 수업 진행 과정, 수강자의 수, 수강자의 요구에 따라 수업 내용이 다소 바뀔 수도 있으니 의견이 있을 때는 주저 말고 제안하기 바랍니다.\n\n4. 특별한 사유가 있어 결석할 경우에는 미리 이유를 말하고, 그 사유서를 일주일 이내에 제출하세요. 기한을 넘기면 인정하지 않습니다.\n\n5. 보고서의 제출 날짜를 반드시 지켜주십시오. 제출 날짜가 지나면 받지 않습니다.\n\n6. 수업 진행을 위한 카페(http:--cafe.daum.net-knuhb)가 있으니 자유롭게 활용하세요.', '장애정도에 따라 필요한 사안이 발생시 최대한 편의 제공함');
INSERT INTO course_info(goals, textbook, description, criteria, notice, disabilities) VALUES ('알고리즘을 설계하고 분석하는 기술을 익히고, 실제 현장에서 많이 만날 수 있는 문제들을 배운 알고리즘을 이용해서 풀어본다.', 'Foundations of Algorithms (Neapolitan & Naimipour)', '강의.\n파워포인트 및 프로젝터', '출석 10%\n강의 참여도 (특히 질문 많이 하는 사람에게 해택있음) 10%\n숙제 20%\n중간시험 30%\n기말시험 30%\n\n\n* 선수과목 - 자료구조', '자료구조에 관한 지식이 많이 필요함. 자료구조 강의를 꼭 듣고 와야함.', '가. 청각장애 학생 : 앞자리 지정석, 강의자료 File 제공(가능한 과목에 한함), 긴급 전달사항은 메모활용 등 \n나. 지체장애 학생 : 시험시간연장 등 \n다. 뇌병변장애 학생 : 시험시간연장, 강의자료 File 제공(가능한 과목에 한함) 등 \n라. 시각장애 학생 : 시험지 확대복사제공 등 \n마. 기타 장애정도에 따라 필요한 사안이 발생시 최대한 편의 제공함');
INSERT INTO course_info(goals, textbook, description, criteria, notice, disabilities) VALUES ('이 과목은 정보기술(IT, Information Technology)와 컴퓨터과학의 기초와 응용에 대하여 다루는데 다음 내용을 포함한다. 즉, 컴퓨터의 구조, 입출력 장치, 운영체제, 응용 소프트웨어, 멀티미디어, 프로그래밍 언어, 데이터베이스, 사회적인 요소 등이다. 그러므로 이 수업을 통하여 IT 와 컴퓨터과학의 일반적인 개념과 미래 사회의 특성을 공부하고 나아가 전자존기를 포함한 모든 IT 분야와 컴퓨터과학 분야의 취업에 도움이 되도록 한다. 물론 IT 대학의 컴퓨터학부, 전자공학부, 전기공학과 등의 전공과목은 물론 대학 내 모든 학과의 학습에 도움이 되는 기초 과목이다.', '교재: 김상욱외 4인, IT 융합과 컴퓨터학개론,홍릉과학출판사, 2014.2\n\n참고문헌: Peter Norton, Computing Fundamentals, Fifth Editon, Glencoe-McGraw-Hill, 2003. \nPeter Norton, Introduction to Computers, Fifth Editon, Glencoe-McGraw-Hill, 2003. \n컴퓨터과학 개론 관련 모든 참고서적이나 웹 사이트\n', '1. 매시간 빔 프로젝터 활용 \n\n2. 강의 진도에 따라 숙제와 시험 예정\n\n3. 매 3주째 월요일 마다 임시시험 (수업 중 안내함) \n\n4. 문제 해결 중심의 대화형 수업 \n\n5. 필요할 때는 원격강좌를 활용할 수 있습니다.\n\n* 위의 모든 사항은 학부행사나 학사일정등 사정에 따라 변할 수 있습니다.', '1. 1 ~5 번의 시험과 숙제(출석 및 태도 20%, 숙제와 임시시험 합 20%, 중간시험 30%, 기말시험 30%)\n2. 발표,토론,질문등 수업 적극 참여학생에 대하여 가산\n3. 결석이 많은 학생에 대하여 감산\n4. 상대평가\n* 위의 모든 사항은 대학사정이나 학사일정등 사정에 따라 변할 수 있습니다.', '1. 프로그래밍 경험이나 능력이 있으면 학습 효과가 좋습니다.\n2. 문제 해결 능력 중심의 ''대화형'' 수업입니다.\n3. 매시간 빔 프로젝터를 활용하므로 예습이 필요합니다.\n4. 진도 문제로 예습을 충실히 하여야 합니다.\n5. 1학년을 위한 기본과목이므로 IT대학 3, 4 학년의 수강을 제한합니다. 단, 한번도 수강한 적이 없거나 특별한 경우에는 담당교수와 상의하세요.\n6. 자율전공부 학생, 컴퓨터과학 복수전공 학생(예정자 포함), 컴퓨터 융합 과목에 관심있는 타학과 학생들의 수강을 환영합니다.\n7. 성적 평가에서 상황에 따라 이 과목을 처음 수강하는 학생과 재수강하는 학생을 분리하여 평가할 수 있습니다(재수강자가 많을 경우)\n8. 필요할 때는 학내 업무용 SNS에 등록하고 활용할 수 있습니다.\n^_^_^_^_^_^_^_^_^_^_^_^_^_^_^_^_^_^_^ ((기타사항))^_^_^_^_^_^_^_^_^_^_^_^_^_^_^_^_^_^_^_^_^_^_^\n* 전화나 메일을 보낼 때는 지성인으로서 학번, 소속, 이름을 밝히고 내용에 예의를 갖추길 바랍니다(하루에도 수백통의 메일을 받습니다. 스팸으로 분리되지 않도록 하세요)\n* 수업도중 통화, 떠들거나 들락거리는 행위등 타인에게 방해되는 행동을하는 경우에는 퇴장이나 및 학점에 반영합니다.\n* 학점 부탁(학점달라, 올려달라, 내려달라, 봐달라 등)은 하지 마세요.\n* 성적은 숙제와 시험결과를 학교 규정에 따라 처리하므로 확정 후에는 일절 변경없습니다.\n* 수강 도중 취직했더라도 수업과 시험 등 모든 일정을 마무리하여야만 성적이 나갑니다.\n* 10분 이상 지각하면 출석을 인정하지 않습니다.\n(( 위의 모든 사항은 학교-대학-학부 행사나 학사일정등에 따라 변할 수 있습니다. ))', '1. 1층 강의실\n2. 원격 강좌로 반복 혹은 개인 학습이나 재택 수업 가능\n3. 우너격강좌용 개인 모바일 단말 기기를 활용할 수 있음(원격강좌)');
INSERT INTO course_info(goals, textbook, description, criteria, notice, disabilities) VALUES ('컴퓨터학부’ 수업에서 전공자 교육에 알맞은 새로운 개념의 교육 방법이 필요하다. 이 과목은 ‘소프트웨어와 문제 해결 기법’을 중심으로 컴퓨터학이 무었인지와 개념을 빨리 인지하도록 한다. 또한 이 과목을 통하여 컴퓨터학 전반에 대하여 학습하도록 하여 컴퓨터학을 전공하는 학생들에게 창의력과 사고하는 방법을 인지 및 습득하도록 한다. 결과적으로 학생들에게 미흡할 수 있는 창의력을 문제 해결 기법을 중심으로 하여 소프트웨어 개발에 빨리 접근하도록 한다.', '김상욱, 김황수, 김항준, 박세영, 소프트웨어와 문제 해결 기법, xx 출판사, 2015.\n\n\n\n\n기타 필요한 교재', '1. 자기주도형 ''스마트 학습'' 방법\n\n2. 자기주도형 문제 해결 방법으로 각종 필요한 장비 혹은 도구를 활용한다. \n\n\n3. 문제 해결하는 방법을 순차적으로 기술하고 프로그램화하는 능력을 배양한다.\n\n\n4. 단순히 프로그래밍하는 방법을 수업하는 것이 아니다.\n\n\n5. 창의적인 사고를 요하는 수업이며 그 능력을 배양하도록 한다.\n\n\n6. 매 시간 실습 후 보고서 제출\n\n\n\n\n\n* 위의 모든 사항은 학부행사나 학사일정등 사정에 따라 변할 수 있습니다.', '1. 출석(10%), 매 시간 제출한 보고서 및 임시시험의 합(40%), 숙제(10%), 중간고사와 기말고사 합(40%)의 합의 상대평가\n\n2. 수업 및 실습에 적극 참여한 학생, 창의력을 발휘하거나 토론에 열정적인 학생에 대하여 위 1 항 합계점수의 10%안에서 가산할 수 있음. \n\n\n\n\n\n\n** 2017년도 컴퓨터학부 신입생만 수강신청 가능합니다.**\n\n\n\n\n\n* 위의 모든 사항은 대학사정이나 학사일정등 사정에 따라 변할 수 있습니다.', '1. 프로그래밍 경험이나 능력이 있으면 학습 효과가 좋습니다. \n\n2. 1 학년을 위한 기본과목이므로 IT대학 3, 4 학년의 수강을 제한합니다. \n\n\n\n\n\n** 2017년도 컴퓨터학부 신입생만 수강신청 가능합니다.**\n\n\n\n\n\n\n\n\n^_^_^_^_^_^_^_^_^_^_^_^_^_^_^_^_^_^_^ ((기타사항))^_^_^_^_^_^_^_^_^_^_^_^_^_^_^_^_^_^_^_^_^_^_^ \n\n\n* 전화나 메일을 보낼 때는 지성인으로서 학번, 소속, 이름을 밝히고 내용에 예의를 갖추길 바랍니다.\n\n\n* 하루에도 수백통의 메일을 받습니다. 스팸으로 자동 분리되지 않도록 하세요.\n\n\n* 취업, 진로 등 개인 사정으로 ''학점 부탁(학점달라, 올려달라, 내려달라, 봐달라 등)''은 하지 마세요. \n\n\n* 성적은 수강생 전체의 공정성을 위해 숙제와 시험결과를 학교 규정에 따라 처리하므로 확정 후에는 일절 변경없습니다.\n\n\n* 수강 도중 취직했더라도 수업과 시험 등 모든 일정을 마무리하여야만 성적이 나갑니다.\n\n\n\n\n\n(( 위의 모든 사항은 학교-대학-학부 행사나 학사일정등에 따라 변할 수 있습니다. ))', '1. 1층 강의실\n\n2. 반복 혹은 개인 학습 가능');

INSERT INTO course(title, code, credits, department, semester, categories, instructor, hours, location, phone_email, office_hours, language, fk_course_info_id) VALUES ('동물생리학', 'ANSC432001', 3, '생물학전공', '20172', '전공', '손종경', '화8B9A9B/목8B9A9B', '생물학관318', '** 통합정보시스템 로그인- 수업-성적- 수업- "강의담당교수조회"에서 확인 가능함.', null, '한국어', 1);
INSERT INTO course(title, code, credits, department, semester, categories, instructor, hours, location, phone_email, office_hours, language, fk_course_info_id) VALUES ('고고학실습', 'ARAN316001', 3, '고고인류학과', '20172', '전공', '이성주', '월8B9A9B/수8B9A9B', '제4합동강의동403', '** 통합정보시스템 로그인- 수업-성적- 수업- "강의담당교수조회"에서 확인 가능함.', null, '한국어', 2);
INSERT INTO course(title, code, credits, department, semester, categories, instructor, hours, location, phone_email, office_hours, language, fk_course_info_id) VALUES ('문화 기술 개론', 'CLTR263001', 3, '컴퓨터학부', '20171', '기본소양', '김항준', '월1A1B2A/수7A7B8A', '공대9호관418', '** 통합정보시스템 로그인- 수업-성적- 수업- "강의담당교수조회"에서 확인 가능함.', null, '한국어', 3);
INSERT INTO course(title, code, credits, department, semester, categories, instructor, hours, location, phone_email, office_hours, language, fk_course_info_id) VALUES ('물리학 I', 'CLTR213030', 3, '컴퓨터학부', '20171', '전공기반', '이성엽', '화2B3A3B/목1A1B2A', '공대9호관417', '** 통합정보시스템 로그인- 수업-성적- 수업- "강의담당교수조회"에서 확인 가능함.', null, '한국어', 4);
INSERT INTO course(title, code, credits, department, semester, categories, instructor, hours, location, phone_email, office_hours, language, fk_course_info_id) VALUES ('실용화법', 'CLTR003004', 3, '컴퓨터학부', '20171', '기본소양', '정수진', '월2B3A3B/금1A1B2A', '공대9호관417', '** 통합정보시스템 로그인- 수업-성적- 수업- "강의담당교수조회"에서 확인 가능함.', null, '한국어', 5);
INSERT INTO course(title, code, credits, department, semester, categories, instructor, hours, location, phone_email, office_hours, language, fk_course_info_id) VALUES ('알고리즘1', 'COMP319003', 3, '컴퓨터학부', '20171', '공학전공', '유관우', '화8B9A9B/목8B9A9B', '공대9호관418', '** 통합정보시스템 로그인- 수업-성적- 수업- "강의담당교수조회"에서 확인 가능함.', null, '한국어', 6);
INSERT INTO course(title, code, credits, department, semester, categories, instructor, hours, location, phone_email, office_hours, language, fk_course_info_id) VALUES ('컴퓨터학개론', 'ITEC201009', 3, '컴퓨터학부', '20171', '공학전공', '이호경', '월7A7B8A/수8B9A9B', 'IT대학4호관(제2학생회관)101', '** 통합정보시스템 로그인- 수업-성적- 수업- "강의담당교수조회"에서 확인 가능함.', null, '한국어', 7);
INSERT INTO course(title, code, credits, department, semester, categories, instructor, hours, location, phone_email, office_hours, language, fk_course_info_id) VALUES ('소프트웨어와 문제해결\n', 'COMP209003', 3, '컴퓨터학부', '20171', '공학전공', '김항준', '수1A1B2A2B3A3B4A4B', '공대12호관207', '** 통합정보시스템 로그인- 수업-성적- 수업- "강의담당교수조회"에서 확인 가능함.', null, '한국어', 8);

INSERT INTO timetable(name, serial_number, semester, fk_user_id) VALUES('test', '0f047c0b528b757b473877a9b9fcec79', '20171', 1);

INSERT INTO course_timetable(fk_timetable_id, fk_course_id) VALUES(1, 1);
INSERT INTO course_timetable(fk_timetable_id, fk_course_id) VALUES(1, 2);
INSERT INTO course_timetable(fk_timetable_id, fk_course_id) VALUES(1, 3);
INSERT INTO course_timetable(fk_timetable_id, fk_course_id) VALUES(1, 4);
INSERT INTO course_timetable(fk_timetable_id, fk_course_id) VALUES(1, 5);


INSERT INTO hours(day, start_time, end_time) VALUES('MON', '07:30', '08:45');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '08:00', '09:00');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '09:00', '09:30');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '09:30', '10:00');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '10:00', '10:30');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '10:30', '11:00');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '11:00', '11:30');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '11:30', '12:00');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '12:00', '12:30');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '12:30', '13:00');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '13:00', '13:30');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '13:30', '14:00');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '14:00', '14:30');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '14:30', '15:00');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '15:00', '15:30');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '15:30', '16:00');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '16:00', '16:30');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '16:30', '17:00');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '17:00', '17:30');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '17:30', '18:00');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '18:00', '18:30');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '18:30', '19:00');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '19:00', '19:30');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '19:30', '20:00');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '20:00', '20:30');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '20:30', '21:00');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '21:00', '21:30');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '21:30', '22:00');
INSERT INTO hours(day, start_time, end_time) VALUES('MON', '22:00', '22:30');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '07:30', '08:45');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '08:00', '09:00');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '09:00', '09:30');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '09:30', '10:00');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '10:00', '10:30');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '10:30', '11:00');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '11:00', '11:30');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '11:30', '12:00');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '12:00', '12:30');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '12:30', '13:00');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '13:00', '13:30');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '13:30', '14:00');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '14:00', '14:30');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '14:30', '15:00');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '15:00', '15:30');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '15:30', '16:00');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '16:00', '16:30');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '16:30', '17:00');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '17:00', '17:30');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '17:30', '18:00');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '18:00', '18:30');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '18:30', '19:00');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '19:00', '19:30');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '19:30', '20:00');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '20:00', '20:30');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '20:30', '21:00');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '21:00', '21:30');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '21:30', '22:00');
INSERT INTO hours(day, start_time, end_time) VALUES('TUE', '22:00', '22:30');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '07:30', '08:45');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '08:00', '09:00');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '09:00', '09:30');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '09:30', '10:00');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '10:00', '10:30');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '10:30', '11:00');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '11:00', '11:30');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '11:30', '12:00');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '12:00', '12:30');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '12:30', '13:00');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '13:00', '13:30');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '13:30', '14:00');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '14:00', '14:30');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '14:30', '15:00');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '15:00', '15:30');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '15:30', '16:00');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '16:00', '16:30');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '16:30', '17:00');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '17:00', '17:30');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '17:30', '18:00');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '18:00', '18:30');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '18:30', '19:00');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '19:00', '19:30');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '19:30', '20:00');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '20:00', '20:30');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '20:30', '21:00');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '21:00', '21:30');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '21:30', '22:00');
INSERT INTO hours(day, start_time, end_time) VALUES('WED', '22:00', '22:30');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '07:30', '08:45');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '08:00', '09:00');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '09:00', '09:30');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '09:30', '10:00');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '10:00', '10:30');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '10:30', '11:00');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '11:00', '11:30');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '11:30', '12:00');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '12:00', '12:30');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '12:30', '13:00');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '13:00', '13:30');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '13:30', '14:00');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '14:00', '14:30');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '14:30', '15:00');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '15:00', '15:30');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '15:30', '16:00');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '16:00', '16:30');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '16:30', '17:00');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '17:00', '17:30');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '17:30', '18:00');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '18:00', '18:30');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '18:30', '19:00');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '19:00', '19:30');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '19:30', '20:00');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '20:00', '20:30');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '20:30', '21:00');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '21:00', '21:30');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '21:30', '22:00');
INSERT INTO hours(day, start_time, end_time) VALUES('THU', '22:00', '22:30');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '07:30', '08:45');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '08:00', '09:00');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '09:00', '09:30');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '09:30', '10:00');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '10:00', '10:30');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '10:30', '11:00');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '11:00', '11:30');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '11:30', '12:00');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '12:00', '12:30');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '12:30', '13:00');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '13:00', '13:30');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '13:30', '14:00');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '14:00', '14:30');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '14:30', '15:00');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '15:00', '15:30');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '15:30', '16:00');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '16:00', '16:30');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '16:30', '17:00');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '17:00', '17:30');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '17:30', '18:00');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '18:00', '18:30');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '18:30', '19:00');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '19:00', '19:30');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '19:30', '20:00');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '20:00', '20:30');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '20:30', '21:00');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '21:00', '21:30');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '21:30', '22:00');
INSERT INTO hours(day, start_time, end_time) VALUES('FRI', '22:00', '22:30');


INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(1, 47);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(1, 48);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(1, 49);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(1, 105);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(1, 106);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(1, 107);

INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(2, 18);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(2, 19);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(2, 20);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(2, 76);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(2, 77);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(2, 78);

INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(3, 3);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(3, 4);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(3, 5);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(3, 73);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(3, 74);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(3, 75);

INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(4, 35);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(4, 36);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(4, 37);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(4, 90);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(4, 91);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(4, 92);

INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(5, 6);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(5, 7);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(5, 8);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(5, 119);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(5, 120);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(5, 121);

INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(6, 47);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(6, 48);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(6, 49);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(6, 105);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(6, 106);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(6, 107);

INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(7, 15);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(7, 16);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(7, 17);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(7, 76);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(7, 77);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(7, 78);

INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(8, 61);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(8, 62);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(8, 63);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(8, 64);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(8, 65);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(8, 66);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(8, 67);
INSERT INTO course_hours(fk_course_id, fk_hours_id) VALUES(8, 68);

INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac', 2, '2017-08-14 13:00:00', 1, 1);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus', 1, '2017-08-13 13:00:00', 2, 1);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla', 5, '2017-08-14 13:00:00', 3, 1);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec', 5, '2017-08-12 13:00:00', 4, 1);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('phasellus sit amet erat nulla tempus vivamus in felis eu sapien', 3, '2017-08-11 13:00:00', 5, 1);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet', 5, '2017-08-12 13:00:00', 1, 2);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget', 0, '2017-08-11 13:00:00', 2, 2);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('lorem ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut', 3, '2017-08-11 13:00:00', 3, 2);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis', 2, '2017-08-08 13:00:00', 4, 2);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar', 1, '2017-08-10 13:00:00', 5, 2);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit', 3, '2017-08-14 13:00:00', 1, 3);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut', 1, '2017-08-06 13:00:00', 2, 3);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus', 1, '2017-08-07 13:00:00', 3, 3);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis', 2, '2017-08-07 13:00:00', 4, 3);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan', 1, '2017-08-14 13:00:00', 5, 3);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis', 0, '2017-08-05 13:00:00', 1, 4);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed', 5, '2017-08-03 13:00:00', 2, 4);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at', 2, '2017-08-02 13:00:00', 3, 4);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut', 0, '2017-08-02 13:00:00', 4, 4);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('a suscipit nulla elit ac nulla sed vel enim sit', 5, '2017-08-14 13:00:00', 5, 4);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('lorem ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum', 5, '2017-08-03 13:00:00', 1, 5);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque', 3, '2017-08-04 13:00:00', 2, 5);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis', 1, '2017-08-07 13:00:00', 3, 5);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel', 5, '2017-08-14 13:00:00', 4, 5);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante', 1, '2017-08-04 13:00:00', 5, 5);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus', 5, '2017-08-12 13:00:00', 1, 6);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec', 2, '2017-08-12 13:00:00', 2, 6);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit', 4, '2017-08-13 13:00:00', 3, 6);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci', 3, '2017-08-13 13:00:00', 4, 6);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum', 5, '2017-08-13 13:00:00', 5, 6);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero', 5, '2017-08-08 13:00:00', 1, 7);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et', 2, '2017-08-08 13:00:00', 2, 7);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum', 1, '2017-08-09 13:00:00', 3, 7);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem', 2, '2017-08-09 13:00:00', 4, 7);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at', 2, '2017-08-05 13:00:00', 5, 7);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non', 0, '2017-08-05 13:00:00', 1, 8);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis', 1, '2017-08-03 13:00:00', 2, 8);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non', 1, '2017-08-02 13:00:00', 3, 8);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet', 2, '2017-01-14 13:00:00', 4, 8);
INSERT INTO rating (comment, star, date_time, fk_user_id, fk_course_id) VALUES ('pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus', 1, '2017-07-14 13:00:00', 5, 8);